name: Build and Test

# Trigger the workflow on push and pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies (cmake, g++, and other build tools)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # Build and test string_compression
      - name: Build and test string_compression
        run: |
          cd Labs1/string_compression
          mkdir -p build
          cd build
          cmake ..
          make
          ./test_string_compression

      # Build and test array_reversal
      - name: Build and test array_reversal
        run: |
          cd Labs1/array_reversal
          mkdir -p build
          cd build
          cmake ..
          make
          ./test_array_reversal

      # Build and test palindrome_checker
      - name: Build and test palindrome_checker
        run: |
          cd Labs1/palindrome_checker
          mkdir -p build
          cd build
          cmake ..
          make
          ./test_palindrome
